services:
  - type: web
    name: python-bridge-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python fx/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 