services:
  # Web service
  - type: web
    name: fx-trading-bot
    env: python
    region: oregon
    plan: free
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn enhanced_trading:app --host 0.0.0.0 --port $PORT
    # Define environment variables (secrets should be configured in Render UI)
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: OANDA_API_URL
        value: https://api-fxtrade.oanda.com/v3
      - key: OANDA_ENVIRONMENT
        value: practice
      - key: TRADE_24_7
        value: "true"
      - key: MAX_RETRIES
        value: "3"
      - key: MAX_DAILY_LOSS
        value: "0.20"
      - key: MAX_RISK_PERCENTAGE
        value: "2.0"
      - key: ENABLE_ADVANCED_LOSS_MANAGEMENT
        value: "true"
      - key: ENABLE_MULTI_STAGE_TP
        value: "true"
      - key: ENABLE_MARKET_STRUCTURE_ANALYSIS
        value: "true"
      - key: OANDA_ACCOUNT_ID
        sync: false
      - key: OANDA_API_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false

  # Optional: Database service if needed
  # - type: pserv
  #   name: fx-trading-db
  #   env: docker
  #   repo: https://github.com/render-examples/postgresql.git
  #   envVars:
  #     - key: POSTGRES_USER
  #       sync: false
  #     - key: POSTGRES_PASSWORD
  #       sync: false
  #     - key: POSTGRES_DB
  #       value: trading_data 