services:
  - type: web
    name: auto-trade
    env: python
    runtime: python-3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info --timeout-keep-alive 60 --limit-concurrency 100
    envVars:
      - key: OANDA_ACCOUNT_ID
        fromSecret: OANDA_ACCOUNT_ID_2
      - key: OANDA_ACCESS_TOKEN
        fromSecret: OANDA_ACCESS_TOKEN_2
      - key: OANDA_ENVIRONMENT
        value: practice
      - key: DATABASE_URL
        fromSecret: NEON_DATABASE_URL
      - key: NOTIFICATION_WEBHOOK_URL
        fromSecret: DISCORD_WEBHOOK_URL_2
      - key: ALPHA_VANTAGE_API_KEY
        fromSecret: ALPHA_VANTAGE_API_KEY
      - key: CRYPTO_HANDLER_ENABLED
        value: "true"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /health
    autoDeploy: yes

databases:
  - name: auto-trade-db
    plan: starter
    databaseName: auto_trade
    ipAllowList: [] 