services:
  - type: web
    name: auto-trade
    env: python
    runtime: python-3.11.7
    buildCommand: |
      echo "==> Build started: $(date)"
      # Install TA-Lib C-library dependencies
      apt-get update && apt-get install -y --no-install-recommends wget build-essential
      wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
      tar -xzf ta-lib-0.4.0-src.tar.gz
      cd ta-lib/
      ./configure --prefix=/usr
      make
      make install
      cd ..
      
      # Now install python dependencies
      echo "==> Python version: $(python --version)"
      pip install --upgrade pip wheel setuptools
      
      # First, install TA-Lib from source, allowing it to build
      echo "==> Installing TA-Lib from source..."
      pip install TA-Lib
      
      # Then, install the rest of the requirements
      echo "==> Installing remaining packages..."
      pip install --no-cache-dir -r requirements.txt
      
      echo "==> Build completed successfully: $(date)"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info --timeout-keep-alive 60 --limit-concurrency 100
    envVars:
      - key: PORT
        fromService:
          type: web
          name: auto-trade
          envVarKey: PORT
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: auto-trade-db
          property: connectionString
      - key: OANDA_ACCOUNT
        sync: false
      - key: OANDA_TOKEN
        sync: false
      - key: OANDA_ENVIRONMENT
        value: practice
      - key: ACTIVE_EXCHANGE
        value: oanda
      - key: DEFAULT_RISK_PERCENTAGE
        value: 20.0
      - key: MAX_RISK_PERCENTAGE
        value: 20.0
      - key: MAX_PORTFOLIO_HEAT
        value: 70.0
      - key: MAX_DAILY_LOSS
        value: 50.0
      - key: DB_MIN_CONNECTIONS
        value: 5
      - key: DB_MAX_CONNECTIONS
        value: 20
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: auto-trade-db
    plan: starter
    databaseName: auto_trade
    ipAllowList: []
