services:
  - type: web
    name: auto-trade
    env: python
    runtime: python-3.11.7
    buildCommand: |
      echo "==> Build started: $(date)"
      echo "==> Python version: $(python --version)"
      
      # Fast, reliable build process for institutional trading system
      pip install --upgrade pip wheel setuptools
      pip install --only-binary=:all: --no-cache-dir -r requirements.txt
      
      echo "==> Build completed successfully: $(date)"
    startCommand: uvicorn auto_trade.main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info --timeout-keep-alive 60 --limit-concurrency 100
    envVars:
      - key: PORT
        fromService:
          type: web
          name: auto-trade
          envVarKey: PORT
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: auto-trade-db
          property: connectionString
      - key: OANDA_ACCOUNT_ID
        sync: false
      - key: OANDA_ACCESS_TOKEN
        sync: false
      - key: OANDA_ENVIRONMENT
        value: practice
      - key: ACTIVE_EXCHANGE
        value: oanda
      - key: DEFAULT_RISK_PERCENTAGE
        value: 20.0
      - key: MAX_RISK_PERCENTAGE
        value: 20.0
      - key: MAX_PORTFOLIO_HEAT
        value: 70.0
      - key: MAX_DAILY_LOSS
        value: 50.0
      - key: DB_MIN_CONNECTIONS
        value: 5
      - key: DB_MAX_CONNECTIONS
        value: 20
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: auto-trade-db
    plan: starter
    databaseName: auto_trade
    ipAllowList: [] 