services:
  - type: web
    name: auto-trade
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python python_bridge.py
    envVars:
      - key: OANDA_ACCOUNT_ID
        sync: false
      - key: OANDA_API_TOKEN
        sync: false
